import type { GameCommand } from '../commands/types';
import { clampSim } from './coords';
import { createGame as makeGame } from './create';
import { stepGame } from './step';
import type { ApiResult, DepthOrder, GamePhase, GameState, Point, SpeedOrder, WeaponMode } from './types';

export const createGame = (seed?: number): GameState => makeGame(seed);
export const startMission = (state: GameState): GameState => ({ ...state, phase: 'playing' });
export const restartGame = (state: GameState): GameState => ({ ...makeGame(state.seed), phase: 'playing' });
export const setPhase = (state: GameState, phase: GamePhase): GameState => ({ ...state, phase });
export const setWeapon = (state: GameState, weapon: WeaponMode): GameState => ({ ...state, weaponMode: weapon });
export const toggleDebugFacing = (state: GameState): GameState => ({ ...state, debugFacing: !state.debugFacing });
export const setDepthOrder = (state: GameState, order: DepthOrder): GameState => stepGame(state, [{ type: 'setDepthOrder', order }], 0);
export const setSpeedOrder = (state: GameState, order: SpeedOrder): GameState => stepGame(state, [{ type: 'setSpeedOrder', order }], 0);
export const toggleSilentRunning = (state: GameState): GameState => ({ ...state, submarine: { ...state.submarine, silentRunning: !state.submarine.silentRunning } });
export const toggleScope = (state: GameState): GameState => ({ ...state, submarine: { ...state.submarine, scopeUp: !state.submarine.scopeUp } });
export const toggleSnorkel = (state: GameState): GameState => ({ ...state, submarine: { ...state.submarine, snorkel: !state.submarine.snorkel } });
export const toggleTorpedoSpread = (state: GameState): GameState => ({ ...state, torpedoSpread: !state.torpedoSpread });
export const setAutopilot = (state: GameState, waypoint: Point): GameState => stepGame(state, [{ type: 'setAutopilot', waypoint }], 0);
export const cancelAutopilot = (state: GameState): GameState => stepGame(state, [{ type: 'cancelAutopilot' }], 0);
export const orderMove = (state: GameState, waypoint: Point): GameState => setAutopilot(state, waypoint);
export const selectTarget = (): ApiResult => ({ ok: false, reason: 'not_implemented' });
export const clearEngagement = (): ApiResult => ({ ok: false, reason: 'not_implemented' });
export const detachCamera = (): ApiResult => ({ ok: false, reason: 'not_implemented' });
export const deployCountermeasure = (): ApiResult => ({ ok: false, reason: 'not_implemented' });
export const fireWeapon = (): ApiResult => ({ ok: false, reason: 'not_implemented' });
export const sonarPulse = (): ApiResult => ({ ok: false, reason: 'not_implemented' });
export const updateGame = (state: GameState, commands: GameCommand[] = [], dt = 1 / 60): GameState => stepGame(state, commands, dt);
export const findShip = (state: GameState, id: string) => state.ships.find((ship) => ship.id === id) ?? null;
export const pickShipAt = (state: GameState, point: Point, radius = 1) => state.ships.find((ship) => Math.hypot(ship.x - point.x, ship.y - point.y) <= radius) ?? null;
export const pickShipAtScreen = (): ApiResult => ({ ok: false, reason: 'not_implemented' });
export const snapToNavigable = (point: Point): Point => ({ x: clampSim(point.x), y: clampSim(point.y) });
export const applyHostSeed = (state: GameState, seed: number): GameState => ({ ...state, seed: seed >>> 0, rngState: seed >>> 0, terrainSeed: seed >>> 0 });
